from datetime import datetime
from typing import Optional

from sqlalchemy import String, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import JSONB, ARRAY
from pgvector.sqlalchemy import Vector

from app.db.database import Base


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    email: Mapped[Optional[str]] = mapped_column(String)


class VoiceProfile(Base):
    __tablename__ = "voice_profiles"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    user_id: Mapped[str] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    name: Mapped[str] = mapped_column(String, nullable=False)
    embedding = mapped_column(Vector(192))  # SpeechBrain ECAPA-TDNN 192-dimensional vector

    user: Mapped["User"] = relationship()


class MeetingSpeakerMapping(Base):
    __tablename__ = "meeting_speaker_mappings"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    raw_speaker_name: Mapped[str] = mapped_column(String, primary_key=True)
    user_id: Mapped[str] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))

    meeting: Mapped["Meeting"] = relationship()
    user: Mapped["User"] = relationship()


class Meeting(Base):
    __tablename__ = "meetings"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    recorded_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    participants: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    
    # URL to the original raw .vtt file in AWS S3 or Google Cloud Storage
    raw_vtt_url: Mapped[Optional[str]] = mapped_column(String)
    raw_vtt_content: Mapped[Optional[str]] = mapped_column(String)
    audio_filepath: Mapped[Optional[str]] = mapped_column(String)
    audio_url: Mapped[Optional[str]] = mapped_column(String)
    status: Mapped[str] = mapped_column(String, default="Processing")
    duration: Mapped[str] = mapped_column(String, default="45m")
    
    # Relationships
    transcript: Mapped["MeetingTranscript"] = relationship(back_populates="meeting", uselist=False, cascade="all, delete-orphan")
    highlights: Mapped[list["MeetingHighlight"]] = relationship(back_populates="meeting", cascade="all, delete-orphan")


class MeetingTranscript(Base):
    __tablename__ = "meeting_transcripts"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    
    # This stores the array of dicts: [{"id": "msg_1", "speaker": "Anish", "text": "...", "start": 1.2, "end": 4.5}]
    cleaned_transcript: Mapped[list[dict]] = mapped_column(JSONB, default=list)
    
    # Relationship
    meeting: Mapped["Meeting"] = relationship(back_populates="transcript")


class MeetingHighlight(Base):
    __tablename__ = "meeting_highlights"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"))
    
    # "action_item", "decision", "risk", "proposal", etc.
    highlight_type: Mapped[str] = mapped_column(String, index=True)
    
    # The condensed sentence generated by the LLM
    text: Mapped[str] = mapped_column(String)
    
    # If the LLM identifies an owner (for action items)
    owner: Mapped[Optional[str]] = mapped_column(String)
    
    # Traceability: The utterance IDs from the cleaned_transcript
    source_ids: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)

    # Relationship
    meeting: Mapped["Meeting"] = relationship(back_populates="highlights")


class MeetingKeyMoment(Base):
    __tablename__ = "meeting_key_moments"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    km_id: Mapped[str] = mapped_column(String)
    moment_type: Mapped[str] = mapped_column(String)
    text: Mapped[str] = mapped_column(String)
    confidence: Mapped[float] = mapped_column(default=0.8)
    source_utterance_ids: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    source_doc_refs: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)


class MeetingTopic(Base):
    __tablename__ = "meeting_topics"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    topics_data: Mapped[dict] = mapped_column(JSONB, default=dict)


class MeetingSummaryRecap(Base):
    __tablename__ = "meeting_summary_recaps"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    markdown_report: Mapped[str] = mapped_column(String)
    citations_used: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)


class MeetingActionItem(Base):
    __tablename__ = "meeting_action_items"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    text: Mapped[str] = mapped_column(String)
    owner: Mapped[Optional[str]] = mapped_column(String)
    deadline: Mapped[Optional[str]] = mapped_column(String)
    confidence: Mapped[float] = mapped_column(default=0.8)
    source_utterance_ids: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    source_key_moment_ids: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    source_doc_refs: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)


class MeetingInferredInsight(Base):
    __tablename__ = "meeting_inferred_insights"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    insights_data: Mapped[dict] = mapped_column(JSONB, default=dict)


class MeetingKnowledgeFact(Base):
    __tablename__ = "meeting_knowledge_facts"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    fact_text: Mapped[str] = mapped_column(String)
    source_key_moment_ids: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    tags: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)


class KnowledgeTag(Base):
    __tablename__ = "knowledge_tags"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    tag_name: Mapped[str] = mapped_column(String, unique=True, index=True)
    embedding = mapped_column(Vector(384))
    usage_count: Mapped[int] = mapped_column(default=1)


class KnowledgeGroup(Base):
    """One row per unique tag. Updated by the pipeline after each meeting is processed.
    Stores LLM-synthesized group-level metadata: title, description, goal, and a progress gist.
    """
    __tablename__ = "knowledge_groups"

    id: Mapped[str] = mapped_column(String, primary_key=True)  # slugified tag name
    tag: Mapped[str] = mapped_column(String, unique=True, index=True)
    group_title: Mapped[Optional[str]] = mapped_column(String)
    group_description: Mapped[Optional[str]] = mapped_column(String)
    group_goal: Mapped[Optional[str]] = mapped_column(String)
    progress_gist: Mapped[Optional[str]] = mapped_column(String)
    meeting_count: Mapped[int] = mapped_column(default=0)
    updated_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)


class MeetingTeamPrep(Base):
    __tablename__ = "meeting_team_prep"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    team_prep_data: Mapped[dict] = mapped_column(JSONB, default=dict)


class MeetingTeamAnalysis(Base):
    __tablename__ = "meeting_team_analysis"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    team_analysis_data: Mapped[dict] = mapped_column(JSONB, default=dict)


class MeetingParticipation(Base):
    __tablename__ = "meeting_participation"

    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), primary_key=True)
    participation_data: Mapped[dict] = mapped_column(JSONB, default=dict)


class MeetingWorkflowTrace(Base):
    __tablename__ = "meeting_workflow_traces"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    step_name: Mapped[str] = mapped_column(String)
    status: Mapped[str] = mapped_column(String)
    input_summary: Mapped[Optional[str]] = mapped_column(String)
    output_summary: Mapped[Optional[str]] = mapped_column(String)
    output_data: Mapped[dict] = mapped_column(JSONB, default=dict)
    execution_time_ms: Mapped[int] = mapped_column(default=0)
    created_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)


class MeetingAttachment(Base):
    __tablename__ = "meeting_attachments"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    filename: Mapped[str] = mapped_column(String, nullable=False)
    mime_type: Mapped[str] = mapped_column(String, nullable=False)
    storage_path: Mapped[Optional[str]] = mapped_column(String)
    slide_count: Mapped[int] = mapped_column(default=0)
    page_count: Mapped[int] = mapped_column(default=0)
    outline: Mapped[dict] = mapped_column(JSONB, default=dict)
    doc_summary: Mapped[Optional[str]] = mapped_column(String)

    meeting: Mapped["Meeting"] = relationship()


class AttachmentChunk(Base):
    __tablename__ = "attachment_chunks"

    chunk_id: Mapped[str] = mapped_column(String, primary_key=True)
    attachment_id: Mapped[str] = mapped_column(ForeignKey("meeting_attachments.id", ondelete="CASCADE"), index=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    
    # "page", "slide", "section"
    locator_type: Mapped[str] = mapped_column(String)
    # The actual page or slide number
    locator_value: Mapped[str] = mapped_column(String)
    title: Mapped[Optional[str]] = mapped_column(String)
    text: Mapped[str] = mapped_column(String)
    char_count: Mapped[int] = mapped_column(default=0)

    attachment: Mapped["MeetingAttachment"] = relationship()


class MeetingDocReference(Base):
    __tablename__ = "meeting_doc_references"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    utterance_id: Mapped[str] = mapped_column(String, index=True)
    speaker: Mapped[str] = mapped_column(String)
    
    attachment_id: Mapped[str] = mapped_column(ForeignKey("meeting_attachments.id", ondelete="CASCADE"))
    chunk_id: Mapped[str] = mapped_column(ForeignKey("attachment_chunks.chunk_id", ondelete="CASCADE"))
    
    reference_type: Mapped[str] = mapped_column(String)
    raw_phrase: Mapped[str] = mapped_column(String)
    confidence: Mapped[float] = mapped_column(default=0.0)
    resolution_method: Mapped[str] = mapped_column(String)


class MeetingSemanticChunk(Base):
    __tablename__ = "meeting_semantic_chunks"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    chunk_type: Mapped[str] = mapped_column(String)
    text: Mapped[str] = mapped_column(String)
    metadata_dict: Mapped[dict] = mapped_column(JSONB, default=dict)
    embedding = mapped_column(Vector(384))  # MiniLM 384-dimensional vector

    meeting: Mapped["Meeting"] = relationship()


class MeetingLink(Base):
    __tablename__ = "meeting_links"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    source_meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    target_meeting_id: Mapped[str] = mapped_column(ForeignKey("meetings.id", ondelete="CASCADE"), index=True)
    similarity_score: Mapped[float] = mapped_column(default=0.0)
    reason: Mapped[str] = mapped_column(String)

    source_meeting: Mapped["Meeting"] = relationship("Meeting", foreign_keys=[source_meeting_id])
    target_meeting: Mapped["Meeting"] = relationship("Meeting", foreign_keys=[target_meeting_id])
